/**
 * The `database` package contains classes which are needed for Jooq code generation.
 * Classes generated by Jooq also belong to this package. It does not depend on other packages.
 */
package ai.neptune.usermanager.database;
